# GitHub Pages Configuration

url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/
  - backups/
  - *.log
  - monitor.sh
  - update.sh
  - cron_setup.txt
  - MONITORING_GUIDE.md
  - SISTEMA_RESUMEN.md

# Include files
include:
  - .htaccess

# SEO settings
title: "Individuación y Creación - Marcos"
description: "Creaciones digitales y escritos reflexivos - Tecnología, filosofía y experiencia personal"
author: "Marcos"
